server:
  port: ${PORT:43573}

spring:
  application:
    name: containerized-rating
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #8. konekcija ka bazi koja se nalazi u dockeru
    #url: jdbc:mysql://megabooker-mysql:3306/db_megabooker
    
    #8. konekcija ka lokalnoj bazi u MySql
    url: jdbc:mysql://localhost:3306/db_megabooker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    
    username: root
    password: stefan
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      #9. konekcija ka dockeru
      #defaultZone: http://discovery:8761/eureka/
      
      #9. konekcija ka eclipsu
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true