server:
  port: ${PORT:43573}
  ssl:
   enabled: true
   key-store: classpath:rating.p12
   key-store-password: sifra
   key-store-type: PKCS12
   key-store-alies: rating(pki)
   trust-store: classpath:ratingTrust.p12
   trust-store-password: sifra
   trust-store-type: PKCS12
   
spring:
  application:
    name: containerized-rating
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #8. konekcija ka bazi koja se nalazi u dockeru
    #url: jdbc:mysql://megabooker-mysql:3306/db_megabooker
    
    #8. konekcija ka lokalnoj bazi u MySql
    url: jdbc:mysql://localhost:3306/db_megabooker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    
    username: root
    password: stefan
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      #9. konekcija ka dockeru
      #defaultZone: http://discovery:8761/eureka/
      
      #9. konekcija ka eclipsu
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    secureVirtualHostName: ${spring.application.name}
    nonSecurePortEnabled: false #TRUE
    securePortEnabled: true #true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}

ribbon:
  eureka:
    enabled: true