spring:
  application:
    name: discovery
    
server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 30
#  serviceUrl:
#    defaultZone: http://localhost:8761  

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.megatravel: DEBUG