spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_megabooker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: stefan
    initialization-mode: always
    continue-on-error: true
    

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
server:
  port: 8452

      